version: "3.8"

services:
  web1:
    image: nginx
    container_name: web1
    ports:
      - "8081:80"
    volumes:
      - ./web1/html:/usr/share/nginx/html:ro
    networks:
      - prometheus_localprom

  web2:
    image: nginx
    container_name: web2
    ports:
      - "8082:80"
    volumes:
      - ./web2/html:/usr/share/nginx/html:ro
    networks:
      - prometheus_localprom

  loadbalancer:
    image: nginx
    container_name: loadbalancer
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web1
      - web2
    networks:
      - prometheus_localprom

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    ports:
      - "9113:9113"
    command: -nginx.scrape-uri http://loadbalancer/nginx_status
    depends_on:
      - loadbalancer
    networks:
      - prometheus_localprom

networks:
  prometheus_localprom:
    external: true  # ✅ Correct place for external flag


